# Generated by Django 4.2.30 on 2026-05-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Emoji para la categoría', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'subcategoría',
                'verbose_name_plural': 'subcategorías',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('categoria', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de familia del catálogo', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('descripcion', models.TextField(blank=True)),
                ('material', models.CharField(blank=True, choices=[('acero', 'Acero al Carbón'), ('galvanizado', 'Galvanizado'), ('inoxidable_304', 'Acero Inoxidable 304'), ('inoxidable_410', 'Acero Inoxidable 410'), ('bronce', 'Bronce'), ('nylon', 'Nylon'), ('plastico', 'Plástico'), ('hule', 'Hule'), ('otro', 'Otro')], max_length=20)),
                ('acabado', models.CharField(blank=True, choices=[('pavonado', 'Pavonado'), ('galvanizado', 'Galvanizado'), ('tropicalizado', 'Tropicalizado'), ('cromado', 'Cromado'), ('sin_acabado', 'Sin Acabado'), ('fosfatado', 'Fosfatado'), ('niquelado', 'Niquelado'), ('otro', 'Otro')], max_length=20)),
                ('norma', models.CharField(blank=True, help_text='Ej: UNC, UNF, Milimétrico', max_length=50)),
                ('grado', models.CharField(blank=True, help_text='Ej: G2, G5, G8, Clase 8.8', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.subcategoria')),
            ],
            options={
                'verbose_name_plural': 'productos',
                'ordering': ['subcategoria', 'nombre'],
            },
        ),
    ]
