# Generated by Django 4.2.30 on 2026-05-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta relativa dentro de MEDIA_ROOT, ej: Tornillos/archivo.png', max_length=300),
        ),
    ]
