# Generated by Django 4.2.30 on 2026-08-18 02:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_precio',
            field=models.BooleanField(default=True, help_text='Si se desactiva, el precio se conserva guardado pero deja de aparecer en el sitio.', verbose_name='mostrar precio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio en pesos (MXN). Déjalo vacío si este producto no maneja precio público.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio'),
        ),
    ]
